config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
  resources :cat_rental_requests, only: [:new, :create] do
    post "approve", on: :member
    post "deny", on: :member
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = %w(black white orange brown)

  validates :birth_date, :color, :name, :sex, :owner, presence: true
  validates :sex, inclusion: %w(M F)
  validates :color, inclusion: COLORS

  has_many :cat_rental_requests, dependent: :destroy
  belongs_to :owner,
    foreign_key: :user_id,
    class_name: :User

  def age
    (Date.today - birth_date).to_i / 365
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  STATUS_OPTIONS = %w(PENDING APPROVED DENIED)

  validates :status, inclusion: { in: STATUS_OPTIONS }
  validates :cat_id, :start_date, :end_date, :status, :user, presence: true

  # CUSTOM VALIDATION
  # Request cannot overlap another approved request for same cat
  validate :does_not_overlap_approved_request

  belongs_to :cat
  belongs_to :user

  def pending?
    self.status == "PENDING"
  end

  def approve!
    self.transaction do
      self.status = "APPROVED"
      self.save!
      self.overlapping_pending_requests.each do |request|
        request.deny!
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def overlapping_requests
    self.cat.cat_rental_requests
      .where.not([
        "end_date < :start_date OR start_date > :end_date",
        { start_date: self.start_date, end_date: self.end_date }
      ]).where.not(id: self.id)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: "PENDING")
  end

  def does_not_overlap_approved_request
    return if self.status == "DENIED"
    if overlapping_approved_requests.any?
      errors[:base] << "Cat is not available for those dates"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  after_initialize :ensure_session_token

  has_many :cats
  has_many :cat_rental_requests

  validates :user_name, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  def self.find_by_credentials(username, password)
    @user = User.find_by_user_name(username)
    @user && @user.is_password?(password) ? @user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    until self.save
      self.session_token = generate_session_token
    end
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def ensure_no_user!
    redirect_to cats_url if current_user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout
    @current_user.reset_session_token! if @current_user
    session[:session_token] = nil
    redirect_to cats_url
  end

  def signed_in?
    !!current_user
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :ensure_cat_owner, only: [:approve, :deny]

  def create
    @request = CatRentalRequest.create(request_params)
    @request.user_id = current_user.id
    if @request.save
      redirect_to cat_url(@request.cat)
    else
      flash.now[:errors] = @request.errors.full_messages
      render :new
    end
  end

  def approve
    @request.approve!
    redirect_to cat_url(@request.cat)
  end

  def deny
    @request.deny!
    redirect_to cat_url(@request.cat)
  end

  private

  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end

  def ensure_cat_owner
    @request = current_user.cats.requests.where(id: params[:request_id])
    redirect_to cats_url unless @request
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :ensure_owner, only: [:edit, :update]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now = @cat.errors.full_messages
      render :edit
    end
  end

  def update
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

  def ensure_owner
    @cat = current_user.cats.where(id: params[:id])
    redirect_to cats_url unless @cat
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_no_user!, only: [:create, :new]

  def new

  end

  def create
    @user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to cats_url
    else
      flash.now[:errors] = ["Invalid username/password"]
      render :new
    end
  end

  def destroy
    logout
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_no_user!

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to cats_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<h3>Request a Cat!</h3>

<form class="" action="<%= cat_rental_requests_url %>" method="post">
  <%= auth_token_input %>
  <select class="" name="cat_rental_request[cat_id]">
    <option disabled selected>--select cat--</option>
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br />

  <label for="start_date">Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" value="" id="start_date">
  <br />

  <label for="end_date">End Date</label>
  <input type="date" name="cat_rental_request[end_date]" value="" id="end_date">
  <br />

  <input type="submit" name="" value="Submit Request">
</form>

app/views/cats/_form.html.erb
<% form_type = cat.persisted? ? "Edit" : "Create" %>
<% action = cat.persisted? ? cat_url(cat) : cats_url %>
<% method = cat.persisted? ? "patch" : "post" %>

<h3><%= "#{form_type} Cat" %></h3>

<%= render "shared/errors" %>

<form class="" action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_token_input %>

  <label for="cat_name">Name</label>
  <input type="text" name="cat[name]" value="<%= cat.name %>" id="cat_name" />
  <br />

  Sex
  <% %w(M F).each do |sex| %>
    <label> <%= sex %>
      <input type="radio" name="cat[sex]" value="<%= sex %>" id="cat_sex" <%= cat.sex == sex ? "checked" : ""%>>
    </label>
  <% end %>
  <br />

  <label for="cat_color">Color</label>
  <select class="" name="cat[color]" id="cat_color">
    <option disabled <%= form_type == "Create" ? "selected" : ""%>> --select-- </option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%= color %>" <%= cat.color == color ? "selected" : ""%>><%= color.capitalize %></option>
    <% end %>
  </select>
  <br />

  <label for="cat_birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" id="cat_birth_date" value="<%= cat.birth_date %>">
  <br />

  <label for="cat_description">Description</label>
  <textarea name="cat[description]" rows="8" cols="40" id="cat_description"><%= cat.description %></textarea>
  <br />

  <input type="submit" value="Create">
</form>

app/views/cats/edit.html.erb
<%= render "form",  cat: @cat %>

app/views/cats/index.html.erb
<h2>Cats</h2>

<% @cats.each do |cat| %>
  <%= link_to cat.name, cat_url(cat.id) %>
  <br>
<% end %>

app/views/cats/new.html.erb
<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h3>
  <%= @cat.name %>
</h3>

<table>
  <tr>
     <th>Age</th>
     <td><%= @cat.age %></td>
  </tr>
  <tr>
     <th>Sex</th>
     <td><%= @cat.sex %></td>
  </tr>
  <tr>
     <th>Color</th>
     <td><%= @cat.color %></td>
  </tr>
</table>
<br />

<h4>Description</h4>

<% if @cat.description %>
<%= @cat.description  %>
<% else %>
No description available for this cat
<% end %>

<br />

<h4>Rental Requests</h4>
<table>
  <tr>
    <th>Requester</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% @cat.cat_rental_requests.includes(:user).order(:start_date).each do |request| %>
    <tr>
      <td> <%= request.user.user_name %></td>
      <td> <%= request.start_date %></td>
      <td> <%= request.end_date %></td>
      <td>
      <% if request.pending?  && @cat.owner == current_user %>
        <%= button_to "Approve", approve_cat_rental_request_url, params: { request_id: request.id } %>
        <%= button_to "Deny", deny_cat_rental_request_url, params: { request_id: request.id } %>
      <% else %>
        <%= request.status %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if signed_in? %>
      Hello, <%= current_user.user_name %>!
      <%= link_to "Logout", session_url, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_url %>
      <%= link_to "Login", new_session_url %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_auth_form.html.erb
<% action = type == "new_user" ? users_url : session_url %>
<% button_text = type == "new_user" ? "Sign Up" : "Sign In" %>

<%= render "shared/errors" %>

<form class="" action="<%= action %>" method="post">
  <%= auth_token_input %>
  <label for="user_username">Username</label>
  <input type="text" name="user[user_name]" value="" id="user_username">

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" value="" id="user_password">

  <input type="submit" value="<%= button_text %>">
</form>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
    <br />
  <% end %>
<% end %>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<%= render "shared/auth_form", type: "new_user" %>